version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: weather-wardrobe-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - WEATHERAPI_KEY=${WEATHERAPI_KEY}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./data:/app/data:rw
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge